import React, { useState } from 'react';
import * as ReactRouterDOM from 'react-router-dom';
import LazyImage from '../components/LazyImage';

const { Link } = ReactRouterDOM;

export interface PortfolioItem {
  id: number;
  title: string;
  year: string;
  py: string;
  image: string;
  category: string;
  // Detail fields (Optional)
  description?: string;
  meta?: { label: string; value: string }[];
  images?: string[];
}

export const mockProjects: PortfolioItem[] = [
  {
    id: 20,
    title: '봉선동 제일풍경채',
    year: '2026',
    py: '33PY',
    image: 'https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bongpong_p.webp',
    category: '30PY',
    description: "미니멀 하이엔드의 정석을 보여주는 30평대 현장입니다. 공간 전체를 아우르는 이지적인 쿨톤 베이스로 시각적 개방감을 극대화하고, 곳곳에 정교하게 설계된 우드 포인트를 더해 하이엔드 특유의 깊이감을 완성했습니다. 톤 정리가 완벽한 캔버스 위에 고객의 센스가 돋보이는 가구와 그림이 배치되어, 시간이 흘러도 질리지 않는 트렌디한 무드를 선사합니다.",
    meta: [
      { label: "LOCATION", value: "Nam-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "114B / 33py" },
      { label: "YEAR", value: "2026" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." },
    ],
    images: [
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp001.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp002.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp003.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp008.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp009.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp015.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp016.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp017.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp050.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp051.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp052.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp053.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp054.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp055.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp056.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp057.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp058.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp065.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp066.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp067.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp068.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp069.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp071.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp1-1.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp72.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp73.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp74.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp75.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp76.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp77.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp78.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp79.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp80.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/bp81.webp"
    ]
  },
  {
    id: 21,
    title: '금호동 호반5차',
    year: '2025',
    py: '35PY',
    image: 'https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh_profile.webp',
    category: '30PY',
    description: "금호동 호반5차 프로젝트는 35평형의 공간을 가장 효율적이고 감각적으로 풀어낸 현장입니다. 따뜻한 베이지 톤을 베이스로 하여 아늑함을 강조하면서도, 간결한 라인 정리로 모던한 엣지를 놓치지 않았습니다. 일상의 편안함이 머무는 공간, 디에이치브랜드만의 섬세한 디테일로 완성했습니다.",
    meta: [
      { label: "LOCATION", value: "Seo-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "116m² / 35py" },
      { label: "YEAR", value: "2025" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." },
    ],
    images: [
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh025.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh026.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh029.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh030.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh031.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh032.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh035.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh036.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh037.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh038.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh039.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh040.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh041.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh042.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh044.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh045.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh046.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh047.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh048.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh049.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh050.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh056.webp",
      "https://exdhgwkudejynccxqdhm.supabase.co/storage/v1/object/public/PORTFOLIO/kh057.webp"
    ]
  },
  {
    id: 18,
    title: '수완 성덕마을 대방3차',
    year: '2025',
    py: '50PY',
    image: 'https://i.postimg.cc/CxBVgt96/sudaepeulopil.png',
    category: '50PY',
    description: "하이엔드 인테리어의 정석적인 모습을 보여주는 수완 대방3차 현장입니다. 완벽하게 톤이 정리된 화이트 뉴트럴 베이스는 그 자체로 훌륭한 캔버스가 되어줍니다. 여기에 고객님의 남다른 센스가 돋보이는 가구와 그림 배치가 더해져, 시간이 지나도 질리지 않는 트렌디함을 완성했습니다. 비움으로써 오히려 풍성해지는 미니멀 럭셔리의 가치를 이 공간에 담았습니다.",
    meta: [
      { label: "LOCATION", value: "Gwangsan-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "165m² / 50py" },
      { label: "YEAR", value: "2025" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." },
    ],
    images: [
      "https://i.postimg.cc/kM6NWyrK/001.jpg",
      "https://i.postimg.cc/662VChsV/008.jpg",
      "https://i.postimg.cc/PqXJrSyh/012.jpg",
      "https://i.postimg.cc/jjx2dMcT/013.jpg",
      "https://i.postimg.cc/ZqwR967Q/014.jpg",
      "https://i.postimg.cc/ZqbnKwHS/015.jpg",
      "https://i.postimg.cc/3r4j2ZMZ/016.jpg",
      "https://i.postimg.cc/Vsr9XFyK/017.jpg",
      "https://i.postimg.cc/3r4j2ZMS/018.jpg",
      "https://i.postimg.cc/7h2gDqMZ/019.jpg",
      "https://i.postimg.cc/LsxXqjQM/027.jpg",
      "https://i.postimg.cc/L51zRmB5/028.jpg",
      "https://i.postimg.cc/Y0W1ktf9/029.jpg",
      "https://i.postimg.cc/SRMWqm7K/030.jpg",
      "https://i.postimg.cc/yNLdJ0pC/039.jpg",
      "https://i.postimg.cc/CKc1ZbrT/040.jpg",
      "https://i.postimg.cc/JhpnyjY8/043.jpg",
      "https://i.postimg.cc/nL3zsqSs/044.jpg",
      "https://i.postimg.cc/GpX2BvgH/045.jpg",
      "https://i.postimg.cc/7brYv9hF/059.jpg",
      "https://i.postimg.cc/PNnrGyJB/061.jpg",
      "https://i.postimg.cc/c6G4qhCP/062.jpg",
      "https://i.postimg.cc/gcnsNWhX/064.jpg",
      "https://i.postimg.cc/G3HKqCDv/070.jpg",
      "https://i.postimg.cc/nVC20Jm4/071.jpg",
      "https://i.postimg.cc/nVC20JmK/072.jpg",
      "https://i.postimg.cc/v8ch3snv/073.jpg",
      "https://i.postimg.cc/KYGrLSFj/076.jpg",
      "https://i.postimg.cc/W4N6rLjb/077.jpg",
      "https://i.postimg.cc/DzvdskFZ/078.jpg",
      "https://i.postimg.cc/SKS78FqJ/079.jpg",
      "https://i.postimg.cc/qv08VVtM/080.jpg",
      "https://i.postimg.cc/FHmj55fH/081.jpg",
      "https://i.postimg.cc/T3GrMMy2/085.jpg",
      "https://i.postimg.cc/Z5c6J73k/086.jpg",
      "https://i.postimg.cc/wjVD9fJ9/114.jpg",
      "https://i.postimg.cc/DzvdskFX/117.jpg",
      "https://i.postimg.cc/tgqtPQyF/123.jpg",
      "https://i.postimg.cc/QM8k5Gsb/129.jpg",
      "https://i.postimg.cc/W1n0sWrb/131.jpg",
      "https://i.postimg.cc/L8TjmCfn/132.jpg",
      "https://i.postimg.cc/25kFvRmG/139.jpg",
      "https://i.postimg.cc/Ls9BfKRN/142.jpg"
    ]
  },
  {
    id: 15,
    title: '수완 새한포유',
    year: '2025',
    py: '36PY',
    image: 'https://i.postimg.cc/1RLkK4L8/peulpil.png',
    category: '30PY',
    description: "수완 새한포유 | Woody & Lovely Home 나무의 따뜻함과 사랑스러운 디테일이 만난 집. 아치형 선반, 원목 다이닝, 그리고 감각적인 소품들이 어우러져 세상에서 가장 포근한 공간을 만들었습니다. '우디크 러블리' 감성 가득한 일상 속 행복을 느껴보세요.",
    meta: [
      { label: "LOCATION", value: "Gwangsan-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "120m² / 36py" },
      { label: "YEAR", value: "2025" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." },
    ],
    images: [
      "https://i.postimg.cc/WzFP1kCf/001.jpg",
      "https://i.postimg.cc/GtWn8p13/002.jpg",
      "https://i.postimg.cc/4d1YQr3y/003.jpg",
      "https://i.postimg.cc/SsGnfwK4/004.jpg",
      "https://i.postimg.cc/PJgnpqkX/012.jpg",
      "https://i.postimg.cc/3NsQ4wHd/013.jpg",
      "https://i.postimg.cc/RCyBbgnS/014.jpg",
      "https://i.postimg.cc/HsMgGbQ0/015.jpg",
      "https://i.postimg.cc/JnQs59hG/023.jpg",
      "https://i.postimg.cc/3rVTbtDh/024.jpg",
      "https://i.postimg.cc/85b7mqC7/025.jpg",
      "https://i.postimg.cc/tJCYS21Y/026.jpg",
      "https://i.postimg.cc/5NzVc8w4/027.jpg",
      "https://i.postimg.cc/pXjHNKDZ/028.jpg",
      "https://i.postimg.cc/vTHcq31W/029.jpg",
      "https://i.postimg.cc/jdfbVyzh/030.jpg",
      "https://i.postimg.cc/L4NqYK71/032.jpg",
      "https://i.postimg.cc/59nHYdGq/033.jpg",
      "https://i.postimg.cc/1tdL2zXM/034.jpg",
      "https://i.postimg.cc/hjYH6Gvp/035.jpg",
      "https://i.postimg.cc/gcNwXF50/036.jpg",
      "https://i.postimg.cc/fWB3tnFd/037.jpg",
      "https://i.postimg.cc/jqZWw098/038.jpg",
      "https://i.postimg.cc/CL5Rbrpy/039.jpg",
      "https://i.postimg.cc/c4CvfkGN/040.jpg",
      "https://i.postimg.cc/PrJC1Vnj/041.jpg",
      "https://i.postimg.cc/rFsD5Z2M/042.jpg",
      "https://i.postimg.cc/ZKQCHPJY/043.jpg",
      "https://i.postimg.cc/tCcYkd9X/044.jpg",
      "https://i.postimg.cc/TYsp0jTY/045.jpg",
      "https://i.postimg.cc/L6WnDkmn/046.jpg",
      "https://i.postimg.cc/Px7B9qJ4/047.jpg",
      "https://i.postimg.cc/j51Gmj2g/048.jpg",
      "https://i.postimg.cc/bwQpn1rp/049.jpg",
      "https://i.postimg.cc/t4hp6FJX/050.jpg",
      "https://i.postimg.cc/0ypPS7jQ/051.jpg",
      "https://i.postimg.cc/9QGC9y0F/052.jpg",
      "https://i.postimg.cc/26tPM5yX/055.jpg",
      "https://i.postimg.cc/gJ7fQ0jQ/056.jpg",
      "https://i.postimg.cc/mkF0sG1j/057.jpg",
      "https://i.postimg.cc/25GYcmnL/058.jpg",
      "https://i.postimg.cc/rpjTnc5S/059.jpg",
      "https://i.postimg.cc/3NDPTH0S/060.jpg",
      "https://i.postimg.cc/WzJQvPqY/061.jpg",
      "https://i.postimg.cc/Bb1d0GPw/062.jpg",
      "https://i.postimg.cc/C5fWgVn9/064.jpg",
      "https://i.postimg.cc/x8bW2SNw/065.jpg",
      "https://i.postimg.cc/0jJLsqJ1/073.jpg",
      "https://i.postimg.cc/xd5QxYL5/100.jpg",
      "https://i.postimg.cc/WzJQvPJv/101.jpg",
      "https://i.postimg.cc/7hTpkyTD/102.jpg",
      "https://i.postimg.cc/sxZtrRZ3/103.jpg",
      "https://i.postimg.cc/1zBSCPDH/104.jpg",
      "https://i.postimg.cc/j2JGbrJs/105.jpg",
      "https://i.postimg.cc/4yhrgTh4/106.jpg",
      "https://i.postimg.cc/MTLhNGH0/107.jpg"
    ]
  },
  {
    id: 12,
    title: '노대동 송화레이크힐',
    year: '2025',
    py: '33PY',
    image: 'https://i.postimg.cc/Pxx6RWmz/nosong.png',
    category: '30PY',
    description: "공간의 화사함과 원목 가구가 주는 편안함이 조화롭게 어우러진 현장입니다. 거실과 주방 곳곳에 배치된 원목 아이템들은 차분한 공간에 생동감을 불어넣으며 가구 그 이상의 오브제 역할을 합니다. 시각적 노이즈를 최소화한 면 정리와 정교한 조명 설계가 더해져, 가구 하나하나의 결이 살아나는 감각적인 주거 공간을 완성했습니다.",
    meta: [
      { label: "LOCATION", value: "Nam-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "111m² / 33py" },
      { label: "YEAR", value: "2025" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/7LgDLycF/001.jpg",
      "https://i.postimg.cc/LszRsMw2/005.jpg",
      "https://i.postimg.cc/jdVpL16R/006.jpg",
      "https://i.postimg.cc/qMfPzFcB/007.jpg",
      "https://i.postimg.cc/7YvFfR16/016.jpg",
      "https://i.postimg.cc/N01Y0wSv/031.jpg",
      "https://i.postimg.cc/xdKYdShk/032.jpg",
      "https://i.postimg.cc/WbRBhymz/033.jpg",
      "https://i.postimg.cc/RVrkNY7k/034.jpg",
      "https://i.postimg.cc/zB8NbcYg/038.jpg",
      "https://i.postimg.cc/bJpPDBf9/040.jpg",
      "https://i.postimg.cc/hjcnz5RL/043.jpg",
      "https://i.postimg.cc/ZKkGCQPz/044.jpg",
      "https://i.postimg.cc/zB8NbcYj/045.jpg",
      "https://i.postimg.cc/xCnQJ4Vg/046.jpg",
      "https://i.postimg.cc/3JMsdqjM/050.jpg",
      "https://i.postimg.cc/vHRJcK7s/051.jpg",
      "https://i.postimg.cc/sXszQNCT/053.jpg",
      "https://i.postimg.cc/PxyjmQd1/057.jpg",
      "https://i.postimg.cc/9MbhGYcd/060.jpg",
      "https://i.postimg.cc/26GD47CF/061.jpg",
      "https://i.postimg.cc/FRp4jVhx/063.jpg",
      "https://i.postimg.cc/RFdBcLvG/066.jpg",
      "https://i.postimg.cc/RFdBcLvP/067.jpg",
      "https://i.postimg.cc/q7807dSM/086.jpg"
    ]
  },
  {
    id: 14,
    title: '수완 영무예다음1차',
    year: '2025',
    py: '33PY',
    image: 'https://i.postimg.cc/6q2TPj6q/suwan-yeongmu.png',
    category: '30PY',
    description: "공간의 가치를 결정짓는 소재와 구조의 힘을 보여주는 프로젝트입니다. 거실 전면에 적용된 대리석 마감은 공간에 깊이감 있는 웅장함을 부여하고, 완전히 달라진 주방 레이아웃은 평수 그 이상의 와이드한 시야를 선사합니다. 소재의 고급스러움과 공간의 효율성이 완벽한 균형을 이루는 현장입니다.",
    meta: [
      { label: "LOCATION", value: "Gwangsan-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "117m² / 33py" },
      { label: "YEAR", value: "2025" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." },
    ],
    images: [
      "https://i.postimg.cc/wvPhfb8P/030.jpg",
      "https://i.postimg.cc/Ss5WTtF3/031.jpg",
      "https://i.postimg.cc/wvPhfb8r/032.jpg",
      "https://i.postimg.cc/T1DnZqTx/034.jpg",
      "https://i.postimg.cc/WzLdJRPb/035.jpg",
      "https://i.postimg.cc/7h3f3BxG/036.jpg",
      "https://i.postimg.cc/0jRzJgqy/037.jpg",
      "https://i.postimg.cc/J0NGNT1h/038.jpg",
      "https://i.postimg.cc/tJxFLt9X/040.jpg",
      "https://i.postimg.cc/2yZnPFCr/041.jpg",
      "https://i.postimg.cc/T1DnZqTY/043.jpg",
      "https://i.postimg.cc/xjJGJYMx/044.jpg",
      "https://i.postimg.cc/NG989YmW/047.jpg",
      "https://i.postimg.cc/dQkRkvGF/048.jpg",
      "https://i.postimg.cc/HWc0cHb1/049.jpg",
      "https://i.postimg.cc/7PG1GDSY/050.jpg",
      "https://i.postimg.cc/FRfSLgdq/051.jpg",
      "https://i.postimg.cc/3RPvC4mZ/052.jpg",
      "https://i.postimg.cc/50ZCqYLS/053.jpg",
      "https://i.postimg.cc/jjSPsrst/054.jpg",
      "https://i.postimg.cc/d0Nd3S1V/061.jpg",
      "https://i.postimg.cc/3wfpNbR4/062.jpg",
      "https://i.postimg.cc/vHXmGxDB/067.jpg",
      "https://i.postimg.cc/zBMntPYN/068.jpg",
      "https://i.postimg.cc/tgcZpZSs/069.jpg",
      "https://i.postimg.cc/pdShRhGD/074.jpg",
      "https://i.postimg.cc/4307s7Lp/075.jpg",
      "https://i.postimg.cc/s2LQsQ67/076.jpg",
      "https://i.postimg.cc/85rF5p9y/096.jpg"
    ]
  },
  {
    id: 16,
    title: '수완 우미린1차',
    year: '2025',
    py: '33PY',
    image: 'https://i.postimg.cc/d3gc0vMN/suwan-umilin1cha.png',
    category: '30PY',
    description: "차가운 세련미와 묵직한 온기가 공존하는 수완 우미린 1차입니다. 거실의 쿨톤 대리석 마감이 주는 도시적인 무드 속에, 주방 전면을 채운 다크우드 텍스처가 시선을 한순간에 압도합니다. 자칫 차가울 수 있는 쿨톤 베이스에 딥한 우드 톤을 과감하게 매치하여, 하이엔드 주거 공간에서만 느낄 수 있는 독보적인 웅장함과 깊이감을 구현했습니다.",
    meta: [
      { label: "LOCATION", value: "Gwangsan-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "113m² / 33py" },
      { label: "YEAR", value: "2025" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/d3gc0vMN/suwan-umilin1cha.png"
    ]
  },
  {
    id: 17,
    title: '수완 중흥s클래스 1차',
    year: '2025',
    py: '36PY',
    image: 'https://i.postimg.cc/htWb9wcy/sujungpeulpil.png',
    category: '30PY',
    description: "군더더기 없는 쿨톤의 베이스로 시각적 개방감과 세련미를 동시에 잡은 수완 중흥 1차 현장입니다. 차가운 듯 정갈한 화이트&그레이 톤앤매너는 공간을 더욱 넓고 깊이 있게 만들어주며, 직선적인 라인 정리와 매끄러운 면 처리가 어우러져 현대적인 감각을 완성합니다. 불필요한 색채를 덜어내고 빛과 여백으로 채운, 미니멀 럭셔리의 정석을 보여주는 공간입니다.",
    meta: [
      { label: "LOCATION", value: "Gwangsan-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "122m² / 36py" },
      { label: "YEAR", value: "2025" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." },
    ],
    images: [
      "https://i.postimg.cc/26hCBVwT/sujung1.png",
      "https://i.postimg.cc/4x0GLz2D/sujung2.png",
      "https://i.postimg.cc/zfDdgMFp/2.png",
      "https://i.postimg.cc/mrZdHqyX/omognun-i-(2).png",
      "https://i.postimg.cc/q7gs0dLV/031.jpg",
      "https://i.postimg.cc/mrhYRGwZ/032.jpg",
      "https://i.postimg.cc/d0D2vKBt/033.jpg",
      "https://i.postimg.cc/TPhVGX9x/034.jpg",
      "https://i.postimg.cc/jjCHKrXK/044.jpg",
      "https://i.postimg.cc/zf3C51jr/045.jpg"
    ]
  },
  {
    id: 6,
    title: '운림동 무등파크',
    year: '2024',
    py: '49PY',
    image: 'https://i.postimg.cc/SsBmT6T5/unlimpofile.png',
    category: '40PY',
    description: "49평형의 광활한 공간감을 대담한 면 분할과 깊이 있는 질감으로 풀어낸 운림동 무등파크입니다. 거실 전면을 채운 딥 우드 월(Wood Wall)은 공간의 중심을 잡아주며 시각적인 웅장함을 선사합니다. 장식을 최소화하고 빛과 소재의 대비에 집중하여, 시간이 흘러도 질리지 않는 프리미엄 주거의 가치를 담았습니다.",
    meta: [
      { label: "LOCATION", value: "Dong-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "162m² / 49py" },
      { label: "YEAR", value: "2024" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/gJkzLcwX/022.jpg",
      "https://i.postimg.cc/LX69g4qP/023.jpg",
      "https://i.postimg.cc/V6Lf0sSN/024.jpg",
      "https://i.postimg.cc/8zQTBmJT/025.jpg",
      "https://i.postimg.cc/mgfTNyzL/026.jpg",
      "https://i.postimg.cc/Dyb2XMzd/027.jpg",
      "https://i.postimg.cc/y8msf3cf/028.jpg",
      "https://i.postimg.cc/vTxd54Gz/029.jpg",
      "https://i.postimg.cc/wx1twFv4/030.jpg",
      "https://i.postimg.cc/7P5CKX6T/031.jpg",
      "https://i.postimg.cc/dQghpdZY/032.jpg",
      "https://i.postimg.cc/ZYvR8R7y/033.jpg",
      "https://i.postimg.cc/rs4wMnRL/034.jpg",
      "https://i.postimg.cc/Y2L969nn/035.jpg",
      "https://i.postimg.cc/6ptpxh9Y/036.jpg",
      "https://i.postimg.cc/bNHqg2QL/037.jpg",
      "https://i.postimg.cc/fRCTz0y0/038.jpg",
      "https://i.postimg.cc/g00cnkLK/039.jpg",
      "https://i.postimg.cc/fyYD6VpB/048.jpg",
      "https://i.postimg.cc/BnS4VQgy/049.jpg",
      "https://i.postimg.cc/L5kFxrZq/050.jpg",
      "https://i.postimg.cc/rFckDFv5/051.jpg",
      "https://i.postimg.cc/5tZcbxBF/052.jpg",
      "https://i.postimg.cc/gkDP8bWq/053.jpg",
      "https://i.postimg.cc/vm1RJ16r/054.jpg",
      "https://i.postimg.cc/VvW2qn3b/055.jpg",
      "https://i.postimg.cc/vHXpD77R/056.jpg",
      "https://i.postimg.cc/s2G8ntkR/057.jpg",
      "https://i.postimg.cc/PJTR5NPt/058.jpg",
      "https://i.postimg.cc/c1Bz57bG/059.jpg",
      "https://i.postimg.cc/mr9X3792/060.jpg",
      "https://i.postimg.cc/CLKcP384/061.jpg",
      "https://i.postimg.cc/RV0gsktX/062.jpg",
      "https://i.postimg.cc/tTSX30PM/075.jpg",
      "https://i.postimg.cc/28X2P0FN/076.jpg"
    ]
  },
  {
    id: 7,
    title: '봉선동 광명메이루즈',
    year: '2024',
    py: '34PY',
    image: 'https://i.postimg.cc/mrP2Gv2z/bongseondong-gwangmyeong.png',
    category: '30PY',
    description: "구조가 가진 개성을 디자인으로 승화시킨 감각적인 현장입니다. 자칫 까다로울 수 있는 특이한 구조를 영리하게 활용하여 훨씬 더 입체적이고 아늑한 무드를 연출했습니다. 거실을 감싸는 묵직한 우드 텍스처와 독특한 레이아웃이 만나 갤러리 같은 세련미와 집 본연의 편안함을 모두 잡은 새로운 제안입니다.",
    meta: [
      { label: "LOCATION", value: "Nam-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "114m² / 34py" },
      { label: "YEAR", value: "2024" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/QxgDGXQT/021.jpg",
      "https://i.postimg.cc/FsXvBfLm/022.jpg",
      "https://i.postimg.cc/NjgcQWDb/023.jpg",
      "https://i.postimg.cc/qMxPD1rX/024.jpg",
      "https://i.postimg.cc/MKwkYhCG/027.jpg",
      "https://i.postimg.cc/GhxWgXrw/028.jpg",
      "https://i.postimg.cc/Jz79fj4V/029.jpg",
      "https://i.postimg.cc/4yT0B9F8/030.jpg",
      "https://i.postimg.cc/brHBMw7S/031.jpg",
      "https://i.postimg.cc/X74h595n/032.jpg",
      "https://i.postimg.cc/pXR7jKj9/038.jpg",
      "https://i.postimg.cc/jSkkB9Fz/039.jpg",
      "https://i.postimg.cc/MGC3pBxw/042.jpg",
      "https://i.postimg.cc/nLyShmZK/043.jpg",
      "https://i.postimg.cc/gJ3SX0kN/044.jpg",
      "https://i.postimg.cc/J4pTBvmY/045.jpg",
      "https://i.postimg.cc/W1KX5Zdx/046.jpg",
      "https://i.postimg.cc/k5bwz582/047.jpg",
      "https://i.postimg.cc/GmNqXD4X/048.jpg",
      "https://i.postimg.cc/c1mhV2Kr/049.jpg",
      "https://i.postimg.cc/nhs19L3D/050.jpg",
      "https://i.postimg.cc/k5KFwp3K/051.jpg",
      "https://i.postimg.cc/s279KNdh/052.jpg",
      "https://i.postimg.cc/JnQ3CHhV/053.jpg",
      "https://i.postimg.cc/Xq7fjNZB/055.jpg",
      "https://i.postimg.cc/3xDgJcwW/056.jpg",
      "https://i.postimg.cc/JzBb42hS/057.jpg",
      "https://i.postimg.cc/LXvPbdy8/059.jpg",
      "https://i.postimg.cc/B6NFVWhb/060.jpg",
      "https://i.postimg.cc/PrCD2R1s/061.jpg",
      "https://i.postimg.cc/7Z72yJBM/062.jpg",
      "https://i.postimg.cc/C1MBDPFT/063.jpg",
      "https://i.postimg.cc/d0jZhPc8/064.jpg",
      "https://i.postimg.cc/QCHFYF9b/065.jpg",
      "https://i.postimg.cc/0jFbT971/066.jpg",
      "https://i.postimg.cc/150Sh9GB/067.jpg"
    ]
  },
  {
    id: 8,
    title: '첨단2지구 한양수자인',
    year: '2024',
    py: '25PY',
    image: 'https://i.postimg.cc/J0DFqW8g/cheom2han-yang.png',
    category: '20PY',
    description: "비움의 미학 속에 사용자의 취향을 채운 컨셉. 특색 있는 레이아웃을 영리하게 활용하여 독립적이면서도 연결된 아늑한 공간감을 구현했습니다. 섬세하게 제작된 우드 가구들은 공간의 구조적 특징과 완벽하게 맞물리며, 미니멀리즘이 주는 평온함 속에 거주자만의 감각적인 라이프스타일을 녹여낸 프로젝트입니다.",
    meta: [
      { label: "LOCATION", value: "Buk-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "84A / 25py" },
      { label: "YEAR", value: "2024" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/Mp8Ly4FD/030.jpg",
      "https://i.postimg.cc/t4HchfMk/031.jpg",
      "https://i.postimg.cc/Mp8Ly4F9/034.jpg",
      "https://i.postimg.cc/K8yWnVHC/035.jpg",
      "https://i.postimg.cc/kgdHxZp0/038.jpg",
      "https://i.postimg.cc/HkCNQKN1/040.jpg",
      "https://i.postimg.cc/T3q4Q9z7/041.jpg",
      "https://i.postimg.cc/Nj7zb43z/042.jpg",
      "https://i.postimg.cc/2SFKTwsM/043.jpg",
      "https://i.postimg.cc/9Qtn1p66/044.jpg",
      "https://i.postimg.cc/htb5MrkN/045.jpg",
      "https://i.postimg.cc/rwCPgj6L/046.jpg",
      "https://i.postimg.cc/y8XbnjqV/047.jpg",
      "https://i.postimg.cc/MpbFt5kK/054.jpg",
      "https://i.postimg.cc/pLY6kCNr/055.jpg",
      "https://i.postimg.cc/bwHBLgXs/061.jpg",
      "https://i.postimg.cc/8zB0w48J/062.jpg",
      "https://i.postimg.cc/mrL6n9R1/063.jpg",
      "https://i.postimg.cc/XvjDP53w/064.jpg",
      "https://i.postimg.cc/DzvYNGFC/069.jpg",
      "https://i.postimg.cc/8CZngCP3/070.jpg",
      "https://i.postimg.cc/HL6P1LkD/071.jpg",
      "https://i.postimg.cc/RFqpSzW0/072.jpg",
      "https://i.postimg.cc/W3tYNPdq/073.jpg",
      "https://i.postimg.cc/X75hB3Q5/078.jpg",
      "https://i.postimg.cc/NfXV2Yp7/079.jpg",
      "https://i.postimg.cc/CL8tnYmk/080.jpg",
      "https://i.postimg.cc/yYR53Bv0/081.jpg",
      "https://i.postimg.cc/7ZyRgcWz/082.jpg",
      "https://i.postimg.cc/VvgJD2FK/022.jpg",
      "https://i.postimg.cc/pL4pGfKw/023.jpg",
      "https://i.postimg.cc/NjS5J6Rz/024.jpg",
      "https://i.postimg.cc/43cnrY57/025.jpg",
      "https://i.postimg.cc/vBdDMGqH/026.jpg",
      "https://i.postimg.cc/wTBM9fVD/027.jpg",
      "https://i.postimg.cc/SxBx7ypd/032.jpg",
      "https://i.postimg.cc/zB5D60vj/033.jpg",
      "https://i.postimg.cc/wvHxZ0Mt/049.jpg",
      "https://i.postimg.cc/vTZYHTW1/053.jpg",
      "https://i.postimg.cc/SR1yX4r1/074.jpg",
      "https://i.postimg.cc/3N1knzZD/075.jpg",
      "https://i.postimg.cc/sxmMwbJP/076.jpg",
      "https://i.postimg.cc/XqLrQtgg/077.jpg"
    ]
  },
  {
    id: 9,
    title: '일곡동 현대',
    year: '2024',
    py: '32PY',
    image: 'https://i.postimg.cc/13Qqsc89/omognun-i.png',
    category: '30PY',
    description: "오래된 구축의 틀을 깨고, 요즘 가장 사랑받는 아이보리 뉴트럴 톤으로 새롭게 태어난 일곡동 현대 24평입니다. 공간 전체를 감싸는 부드러운 컬러감은 유행을 타지 않으면서도 세련된 무드를 유지하는 모두가 선호하는 트렌디한 주거 공간컨셉입니다.",
    meta: [
      { label: "LOCATION", value: "Buk-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "107m² / 32py" },
      { label: "YEAR", value: "2024" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/mkBwcfDT/001.jpg",
      "https://i.postimg.cc/d3s2s2HB/005.jpg",
      "https://i.postimg.cc/Y0DWtJmq/008.jpg",
      "https://i.postimg.cc/Kc0L7gp5/016.jpg",
      "https://i.postimg.cc/Wp5rmJfv/017.jpg",
      "https://i.postimg.cc/mr31PcF7/018.jpg",
      "https://i.postimg.cc/SNwnVL6B/019.jpg",
      "https://i.postimg.cc/L6rJvktv/027.jpg",
      "https://i.postimg.cc/Kvd1Q77y/029.jpg",
      "https://i.postimg.cc/0Nvb18HW/032.jpg",
      "https://i.postimg.cc/SKmNtgJw/038.jpg",
      "https://i.postimg.cc/Tww2Thjr/039.jpg",
      "https://i.postimg.cc/k4pJG9wS/041.jpg",
      "https://i.postimg.cc/4yHJhMFF/042.jpg",
      "https://i.postimg.cc/0y0JQMSh/045.jpg",
      "https://i.postimg.cc/QMNKW8kX/046.jpg",
      "https://i.postimg.cc/Ls4gZ9B9/055.jpg",
      "https://i.postimg.cc/pd0hfwqX/056.jpg",
      "https://i.postimg.cc/wx25WrMZ/081.jpg",
      "https://i.postimg.cc/gjzVzVSr/082.jpg"
    ]
  },
  {
    id: 10,
    title: '수완 대주피오레 1단지',
    year: '2024',
    py: '39PY',
    image: 'https://i.postimg.cc/C1ZYYgw9/sudae1.png',
    category: '30PY',
    description: "선적인 미니멀리즘과 차분한 컬러 팔레트가 어우러진 주방 설계입니다. 거대한 아일랜드를 전면에 배치하여 호텔 라운지 같은 고급스러운 무드를 연출했습니다. 군더더기 없는 면 정리와 매립 조명의 섬세한 조화를 통해, 유행을 타지 않는 정갈하고 모던한 주거 톤을 완성한 수완대주피오레 1단지 현장입니다",
    meta: [
      { label: "LOCATION", value: "Gwangsan-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "132m² C-Type / 39py" },
      { label: "YEAR", value: "2024" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/bNVG9zss/004.jpg",
      "https://i.postimg.cc/CLxB8ZLb/022.jpg",
      "https://i.postimg.cc/BQnLF8QH/023.jpg",
      "https://i.postimg.cc/SN1XfyJ2/024.jpg",
      "https://i.postimg.cc/NfCykg5X/025.jpg",
      "https://i.postimg.cc/kXYVvnBK/030.jpg",
      "https://i.postimg.cc/qMDtxkz2/031.jpg",
      "https://i.postimg.cc/sDHB4VvP/032.jpg",
      "https://i.postimg.cc/3JfyFKd9/033.jpg",
      "https://i.postimg.cc/L6Qq3HnN/035.jpg",
      "https://i.postimg.cc/MK3cmWv9/036.jpg",
      "https://i.postimg.cc/xTpk30cp/037.jpg",
      "https://i.postimg.cc/289q7zVc/038.jpg",
      "https://i.postimg.cc/4yNdpMGv/039.jpg",
      "https://i.postimg.cc/YqD4zphs/040.jpg",
      "https://i.postimg.cc/vTHB5jyW/041.jpg",
      "https://i.postimg.cc/d3t1GXF6/042.jpg",
      "https://i.postimg.cc/J04njg89/043.jpg",
      "https://i.postimg.cc/nrczq5Zx/045.jpg",
      "https://i.postimg.cc/5yN08G1b/046.jpg",
      "https://i.postimg.cc/kGX4WZ99/047.jpg",
      "https://i.postimg.cc/q7jWzZmV/049.jpg",
      "https://i.postimg.cc/Jh197WQr/051.jpg",
      "https://i.postimg.cc/bvzKYjRw/056.jpg",
      "https://i.postimg.cc/bv34sF6Y/057.jpg",
      "https://i.postimg.cc/SRNsc5qy/058.jpg",
      "https://i.postimg.cc/tJCTFfyq/059.jpg",
      "https://i.postimg.cc/fbB1JgHy/062.jpg",
      "https://i.postimg.cc/CKm9z6vK/063.jpg",
      "https://i.postimg.cc/Rhs0dRVm/069.jpg",
      "https://i.postimg.cc/QC4Mmbxs/070.jpg",
      "https://i.postimg.cc/HnZLz2sp/074.jpg",
      "https://i.postimg.cc/HnZLz2sW/077.jpg",
      "https://i.postimg.cc/4yJKBy6z/087.jpg",
      "https://i.postimg.cc/rs8dQs1g/091.jpg",
      "https://i.postimg.cc/3wnzdbL0/093.jpg",
      "https://i.postimg.cc/kGnVfGQQ/095.jpg",
      "https://i.postimg.cc/nrHs0r41/096.jpg",
      "https://i.postimg.cc/JhPSGdTX/098.jpg",
      "https://i.postimg.cc/vm3CcSPf/099.jpg",
      "https://i.postimg.cc/k5fLBhjq/100.jpg"
    ]
  },
  {
    id: 11,
    title: '봉선동 포스코더샵',
    year: '2024',
    py: '55PY',
    image: 'https://i.postimg.cc/hPgm4SYv/bongpo55.png',
    category: '50PY',
    description: "공간의 본질에 집중하여 시간이 지나도 변치 않는 가치를 담은 봉선동 포스코더샵입니다. 복잡한 장식 대신 정교한 선의 미학을 활용하여 주거 공간을 갤러리처럼 연출했습니다. 차분하게 가라앉은 톤앤매너는 일상에 깊은 안식과 평온을 제공합니다.",
    meta: [
      { label: "LOCATION", value: "Nam-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "182m² / 55py" },
      { label: "YEAR", value: "2024" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/v8r2TZ0d/001.jpg",
      "https://i.postimg.cc/VvWKVKJN/005.jpg",
      "https://i.postimg.cc/Dfrp0wx8/008.jpg",
      "https://i.postimg.cc/28fp9tKv/030.jpg",
      "https://i.postimg.cc/xTSrpZ4J/031.jpg",
      "https://i.postimg.cc/X70M1PzZ/032.jpg",
      "https://i.postimg.cc/zX1m2QcH/034.jpg",
      "https://i.postimg.cc/FKzwJX7Z/035.jpg",
      "https://i.postimg.cc/QMzwQY71/036.jpg",
      "https://i.postimg.cc/sXZ8wPP9/039.jpg",
      "https://i.postimg.cc/0QJ3cGGG/040.jpg",
      "https://i.postimg.cc/bNPM9tZd/045.jpg",
      "https://i.postimg.cc/ZKmgxdWs/046.jpg",
      "https://i.postimg.cc/bNR5CwnR/047.jpg",
      "https://i.postimg.cc/Wb7yW1ZS/048.jpg",
      "https://i.postimg.cc/sgDNtC9M/049.jpg",
      "https://i.postimg.cc/rwnPTZQ5/050.jpg",
      "https://i.postimg.cc/nhRPxS0N/053.jpg",
      "https://i.postimg.cc/sg6NzHwH/054.jpg",
      "https://i.postimg.cc/4dtLzfZq/058.jpg",
      "https://i.postimg.cc/5yVPgh22/059.jpg"
    ]
  },
  {
    id: 13,
    title: '수완 성덕마을 대방3차(옥탑)',
    year: '2023',
    py: '50PY',
    image: 'https://i.postimg.cc/sg2Crh9g/sudae3.png',
    category: '50PY',
    description: "최상층 옥탑만이 가질 수 있는 독보적인 구조미를 살린 수완 성덕마을 대방3차 현장입니다. 높은 층고를 따라 흐르는 깔끔한 라인과 우드&화이트의 정교한 균형은 주거 공간을 넘어선 갤러리 같은 무드를 선사합니다. 절제된 디자인 속에 수납 디테일을 녹여내어, 일상의 복잡함은 덜어내고 옥탑 공간의 낭만과 품격만을 남겼습니다.",
    meta: [
      { label: "LOCATION", value: "Gwangsan-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "165m² / 50py" },
      { label: "YEAR", value: "2023" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." },
    ],
    images: [
      "https://i.postimg.cc/8zxK0Jyp/001.jpg",
      "https://i.postimg.cc/X7mkjM9f/002.jpg",
      "https://i.postimg.cc/5NTS4c85/003.jpg",
      "https://i.postimg.cc/xTh3frL3/004.jpg",
      "https://i.postimg.cc/SxHTv2ZQ/010.jpg",
      "https://i.postimg.cc/htNy5zCJ/045.jpg",
      "https://i.postimg.cc/kgL1p6j6/049.jpg",
      "https://i.postimg.cc/T3B74LkD/050.jpg",
      "https://i.postimg.cc/0yhWBMtK/052.jpg",
      "https://i.postimg.cc/DyHPvV1d/053.jpg",
      "https://i.postimg.cc/WbCwNR07/054.jpg",
      "https://i.postimg.cc/dtpjsMGn/056.jpg",
      "https://i.postimg.cc/L8GCbYyf/058.jpg",
      "https://i.postimg.cc/9fT85mSM/059.jpg",
      "https://i.postimg.cc/7L7s8Hch/066.jpg",
      "https://i.postimg.cc/9fT85mSz/073.jpg",
      "https://i.postimg.cc/XvFHSjhr/074.jpg",
      "https://i.postimg.cc/cJY9yxjg/075.jpg",
      "https://i.postimg.cc/zfWtZzMH/076.jpg",
      "https://i.postimg.cc/tgPSQqfV/082.jpg",
      "https://i.postimg.cc/5tv7d4GC/083.jpg",
      "https://i.postimg.cc/WbCwNR0X/084.jpg",
      "https://i.postimg.cc/J4v5rwj6/085.jpg",
      "https://i.postimg.cc/vHktYR52/086.jpg",
      "https://i.postimg.cc/vm9qFYjf/089.jpg",
      "https://i.postimg.cc/5tv7d4GB/090.jpg",
      "https://i.postimg.cc/GhVxL0vS/094.jpg",
      "https://i.postimg.cc/8P9mp8LY/096.jpg",
      "https://i.postimg.cc/9FKYm3yS/098.jpg",
      "https://i.postimg.cc/DyHPvV1H/099.jpg",
      "https://i.postimg.cc/xTh3frLW/100.jpg",
      "https://i.postimg.cc/VLpWfyjQ/101.jpg",
      "https://i.postimg.cc/KvwDGXnh/102.jpg",
      "https://i.postimg.cc/NjX7LNxN/103.jpg",
      "https://i.postimg.cc/g2hqrMKt/111.jpg",
      "https://i.postimg.cc/kgSFDjyZ/114.jpg",
      "https://i.postimg.cc/1z6ChmTc/153.jpg",
      "https://i.postimg.cc/fTpfz4Yd/154.jpg",
      "https://i.postimg.cc/QM54G8PJ/156.jpg",
      "https://i.postimg.cc/8zxK0JyC/158.jpg",
      "https://i.postimg.cc/52D7RYP2/160.jpg",
      "https://i.postimg.cc/DyHPvV1J/163.jpg",
      "https://i.postimg.cc/5NTS4c8Q/164.jpg",
      "https://i.postimg.cc/SN3fS0cz/165.jpg"
    ]
  },
  {
    id: 1,
    title: '수완 성덕마을 대방3차',
    year: '2023',
    py: '50PY',
    image: 'https://i.postimg.cc/MHYhd4VN/Chat-GPT-Image-2026nyeon-2wol-2il-ojeon-10-50-09.png',
    category: '50PY',
    description: "우드와 화이트의 정교한 균형으로 고급스러운 주거 톤을 완성한 수완 성덕마을 대방3차 프로젝트입니다. 아이들의 놀이 공간을 집 전체의 흐름 속에 자연스럽게 녹여내었으며, 간결한 라인과 세심한 수납 디테일을 더해 일상의 편리함과 공간의 품격을 동시에 담았습니다.",
    meta: [
      { label: "LOCATION", value: "Gwangsan-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "165m² / 50py" },
      { label: "YEAR", value: "2023" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." },
    ],
    images: [
      "https://i.postimg.cc/fWvp4G0w/003.jpg",
      "https://i.postimg.cc/vHqKT5zh/009.jpg",
      "https://i.postimg.cc/DwSMXmpF/035.jpg",
      "https://i.postimg.cc/CxRQqdrR/039.jpg",
      "https://i.postimg.cc/q7nD1SdX/040.jpg",
      "https://i.postimg.cc/9fTgLKjN/041.jpg",
      "https://i.postimg.cc/PxQ3jDJN/047.jpg",
      "https://i.postimg.cc/G2x7CDtq/048.jpg",
      "https://i.postimg.cc/sxnTBRpy/054.jpg",
      "https://i.postimg.cc/9FMx6rhB/055.jpg",
      "https://i.postimg.cc/T35tPFh8/056.jpg",
      "https://i.postimg.cc/Xvwxf5wR/057.jpg",
      "https://i.postimg.cc/mDBj8rjF/061.jpg",
      "https://i.postimg.cc/rmjJbLYT/062.jpg",
      "https://i.postimg.cc/VvHFfW8r/063.jpg",
      "https://i.postimg.cc/wxW2Qgmt/064.jpg",
      "https://i.postimg.cc/Wbhn9CGY/066.jpg",
      "https://i.postimg.cc/vHkvChXd/068.jpg",
      "https://i.postimg.cc/Sx9G49tV/069.jpg",
      "https://i.postimg.cc/KYrrk2bF/076.jpg",
      "https://i.postimg.cc/L57zK4tD/078.jpg",
      "https://i.postimg.cc/5yGwd9BG/080.jpg",
      "https://i.postimg.cc/hPk92jPg/082.jpg",
      "https://i.postimg.cc/RVkcgFVq/084.jpg",
      "https://i.postimg.cc/W100Cvhz/085.jpg",
      "https://i.postimg.cc/d0vGKxCQ/088.jpg",
      "https://i.postimg.cc/gJ2RxL4H/093.jpg",
      "https://i.postimg.cc/sXHW7f0T/095.jpg",
      "https://i.postimg.cc/Ss19CQvF/097.jpg",
      "https://i.postimg.cc/PJB8V3H1/099.jpg",
      "https://i.postimg.cc/Fz2JCWmQ/100.jpg",
      "https://i.postimg.cc/dQXd01CW/113.jpg",
      "https://i.postimg.cc/TYDb56js/114.jpg",
      "https://i.postimg.cc/sgChpNwj/121.jpg",
      "https://i.postimg.cc/pLMFD6qK/123.jpg",
      "https://i.postimg.cc/rwGtgNPN/156.jpg",
      "https://i.postimg.cc/7Z1TXnWQ/157.jpg",
      "https://i.postimg.cc/d0qZfZbf/159.jpg",
      "https://i.postimg.cc/43BHRNZX/162.jpg",
      "https://i.postimg.cc/j52wx0dH/163.jpg",
      "https://i.postimg.cc/0jJzSYSN/166.jpg"
    ]
  },
  {
    id: 2,
    title: '수완 대주피오레 1단지',
    year: '2023',
    py: '39PY',
    image: 'https://i.postimg.cc/Hx0yv4nn/image-Dp2.png',
    category: '30PY',
    description: "화이트의 깨끗함과 우드의 무게감이 조화롭게 맞닿은 수완 대주피오레 현장입니다. 군더더기 없는 면 정리와 매립 조명의 섬세한 설계로 주방의 품격을 높였습니다. 특히 직선의 미학이 돋보이는 가구 라인은 일상을 더욱 정돈된 느낌으로 만들어 줍니다.",
    meta: [
      { label: "LOCATION", value: "Gwangsan-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "132m² / 39py" },
      { label: "YEAR", value: "2023" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." },
    ],
    images: [
      "https://i.postimg.cc/v8gRnq4N/015.jpg",
      "https://i.postimg.cc/v8gRnq4q/016.jpg",
      "https://i.postimg.cc/nVj8mRXd/018.jpg",
      "https://i.postimg.cc/FFdtSWYn/019.jpg",
      "https://i.postimg.cc/Y2GcFnvT/021.jpg",
      "https://i.postimg.cc/QN9L74FR/025.jpg",
      "https://i.postimg.cc/MZMkBPck/027.jpg",
      "https://i.postimg.cc/nVj8mRsb/036.jpg",
      "https://i.postimg.cc/HWcGMZJ1/037.jpg",
      "https://i.postimg.cc/7PGvzsCy/041.jpg",
      "https://i.postimg.cc/HWcGMZJg/042.jpg",
      "https://i.postimg.cc/T2L8b7yT/048.jpg",
      "https://i.postimg.cc/sfQFW6Bg/050.jpg",
      "https://i.postimg.cc/7PGvzsCL/051.jpg",
      "https://i.postimg.cc/WpQBwGrc/055.jpg",
      "https://i.postimg.cc/pVgwJf8v/056.jpg",
      "https://i.postimg.cc/HWfq9w5H/059.jpg",
      "https://i.postimg.cc/05LT0Ym9/061.jpg",
      "https://i.postimg.cc/PfBgQWZt/062.jpg",
      "https://i.postimg.cc/d13BzfMv/066.jpg",
      "https://i.postimg.cc/vBTzpKRy/080.jpg",
      "https://i.postimg.cc/Vs3xWqMk/083.jpg",
      "https://i.postimg.cc/9Xv6YdTf/084.jpg",
      "https://i.postimg.cc/c1VpBRYH/088.jpg",
      "https://i.postimg.cc/44rDQ6tY/089.jpg",
      "https://i.postimg.cc/3rPsFXpy/101.jpg",
      "https://i.postimg.cc/FF2MVyck/102.jpg",
      "https://i.postimg.cc/c1VpBRYn/139.jpg",
      "https://i.postimg.cc/T2ZzJVmm/140.jpg",
      "https://i.postimg.cc/jqGp4HNH/142.jpg",
      "https://i.postimg.cc/ZY1Gx83L/143.jpg",
      "https://i.postimg.cc/CLkWPRHB/144.jpg",
      "https://i.postimg.cc/WbgQWd6J/145.jpg",
      "https://i.postimg.cc/tCWLSsth/146.jpg",
      "https://i.postimg.cc/ZKp17WF8/150.jpg",
      "https://i.postimg.cc/KvBdq1r7/152.jpg",
      "https://i.postimg.cc/WbgQWd66/153.jpg"
    ]
  },
  {
    id: 3,
    title: '운암동 벽산블루시안2차',
    year: '2023',
    py: '33PY',
    image: 'https://i.postimg.cc/76858BQd/image-Dp3.png',
    category: '30PY',
    description: "차분하게 가라앉은 톤 위로 간결한 선의 미학을 담아낸 운암 벽산블루밍 프로젝트입니다. 공간 전체를 가로지르는 마그네틱 조명을 포인트로 활용하여 리듬감 있는 시각적 흐름을 완성했습니다. 불필요한 장식은 덜어내고, 빛과 라인만으로 모던한 주거의 품격을 정의합니다.",
    meta: [
      { label: "LOCATION", value: "Buk-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "108m² / 33py" },
      { label: "YEAR", value: "2023" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/xTyysmqJ/029.jpg",
      "https://i.postimg.cc/L6BByPhg/030.jpg",
      "https://i.postimg.cc/sD99nW1Z/031.jpg",
      "https://i.postimg.cc/28f7FGkh/032.jpg",
      "https://i.postimg.cc/fThfjCzY/033.jpg",
      "https://i.postimg.cc/L6M3BD9f/035.jpg",
      "https://i.postimg.cc/xTS3y5fm/036.jpg",
      "https://i.postimg.cc/ZKhxFHbx/040.jpg",
      "https://i.postimg.cc/ZKhxFHbL/041.jpg",
      "https://i.postimg.cc/BQGBcpSm/046.jpg",
      "https://i.postimg.cc/fThfjCzB/047.jpg",
      "https://i.postimg.cc/7YynM9Hs/052.jpg",
      "https://i.postimg.cc/kXdvFsJh/054.jpg",
      "https://i.postimg.cc/MK8mb56L/057.jpg",
      "https://i.postimg.cc/pXtJYCW4/058.jpg",
      "https://i.postimg.cc/TYXJq0dB/059.jpg",
      "https://i.postimg.cc/Gh1xJKLW/060.jpg",
      "https://i.postimg.cc/fThfjCWn/065.jpg",
      "https://i.postimg.cc/bNj9HgYf/066.jpg",
      "https://i.postimg.cc/HsC94zWm/067.jpg",
      "https://i.postimg.cc/8PBByvc0/068.jpg",
      "https://i.postimg.cc/L6BByP5G/079.jpg",
      "https://i.postimg.cc/hPbbCmvk/080.jpg",
      "https://i.postimg.cc/zXSSdh3m/082.jpg",
      "https://i.postimg.cc/VLBB7t5w/083.jpg",
      "https://i.postimg.cc/m2NNd9hT/084.jpg",
      "https://i.postimg.cc/CLHHv8d5/085.jpg",
      "https://i.postimg.cc/J4ccTXty/086.jpg"
    ]
  },
  {
    id: 4,
    title: '봉선동 포스코더샵',
    year: '2023',
    py: '26PY',
    image: 'https://i.postimg.cc/8PJscgQ4/bongpo26.png',
    category: '20PY',
    description: "창밖으로 보이는 초록빛 풍경이 인테리어의 완성도가 되는 곳. 봉선동 포스코의 거실은 자연광을 가득 머금은 화이트 톤과 묵직한 우드 가구가 만나 차분한 안정감을 줍니다. 계절의 변화를 일상에서 가장 가깝게 느낄 수 있도록 가구 배치와 톤앤매너를 섬세하게 조율하여, 머무는 것만으로도 힐링이 되는 주거 공간을 완성했습니다",
    meta: [
      { label: "LOCATION", value: "Nam-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "86m² / 26py" },
      { label: "YEAR", value: "2023" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/k5xb43SL/003.jpg",
      "https://i.postimg.cc/PqmwxsZG/007.jpg",
      "https://i.postimg.cc/9fG7M5T5/008.jpg",
      "https://i.postimg.cc/254Z6RvY/013.jpg",
      "https://i.postimg.cc/PqmwxsZt/028.jpg",
      "https://i.postimg.cc/wBhmv8Jx/029.jpg",
      "https://i.postimg.cc/BnPFr1nN/030.jpg",
      "https://i.postimg.cc/x1Nmwb13/031.jpg",
      "https://i.postimg.cc/13VFkN3c/032.jpg",
      "https://i.postimg.cc/qv6KPCvw/033.jpg",
      "https://i.postimg.cc/JhwXM4s5/034.jpg",
      "https://i.postimg.cc/g09hmkxs/036.jpg",
      "https://i.postimg.cc/fb4dDTVB/043.jpg",
      "https://i.postimg.cc/YScFMqvy/044.jpg",
      "https://i.postimg.cc/vmRnbH4C/045.jpg",
      "https://i.postimg.cc/W4RZTbDR/048.jpg",
      "https://i.postimg.cc/Gp0DdhB1/049.jpg",
      "https://i.postimg.cc/R0cHF5tb/050.jpg",
      "https://i.postimg.cc/VNjC6QtV/058.jpg"
    ]
  },
  {
    id: 5,
    title: '나주 빛가람동 우미린',
    year: '2023',
    py: '29PY',
    image: 'https://i.postimg.cc/W4qtb1kJ/proflie(naju).png',
    category: '20PY',
    description: "취향이 깃든 공간의 가치 우드 홈바와 안방 캠핑 테라스 등 고객의 라이프스타일을 공간의 흐름 안에 자연스럽게 녹여내었으며, 깔끔한 수납 디테일과 감각적인 공간 활용을 통해 일상에 즐거움을 더하는 29평 인테리어의 해답을 제시합니다.",
    meta: [
      { label: "LOCATION", value: "Naju-si, Jeollanam-do" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "99m² / 29py" },
      { label: "YEAR", value: "2023" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." }
    ],
    images: [
      "https://i.postimg.cc/dt0sV0MJ/008.jpg",
      "https://i.postimg.cc/8z2N4B7T/015.jpg",
      "https://i.postimg.cc/8PzY8QhJ/016.jpg",
      "https://i.postimg.cc/JzGzPzK9/017.jpg",
      "https://i.postimg.cc/VkdkDk4h/018.jpg",
      "https://i.postimg.cc/fR3gLc2g/019.jpg",
      "https://i.postimg.cc/vZ1SBrqP/036.jpg",
      "https://i.postimg.cc/2SqX6Qct/037.jpg",
      "https://i.postimg.cc/qRG1Yjqq/039.jpg",
      "https://i.postimg.cc/rsFfLxR3/040.jpg",
      "https://i.postimg.cc/Kjv0yB3C/041.jpg",
      "https://i.postimg.cc/J04pWZHY/042.jpg",
      "https://i.postimg.cc/NfFdJ8cm/043.jpg",
      "https://i.postimg.cc/d026k42V/047.jpg",
      "https://i.postimg.cc/gJGDv8sq/049.jpg",
      "https://i.postimg.cc/pr6Jb7Hd/055.jpg",
      "https://i.postimg.cc/BZYgK8Kv/056.jpg",
      "https://i.postimg.cc/dVdmp4SJ/058.jpg",
      "https://i.postimg.cc/VL2WK34P/065.jpg",
      "https://i.postimg.cc/C1vjktzY/066.jpg",
      "https://i.postimg.cc/nVP4L6yc/067.jpg",
      "https://i.postimg.cc/K8XtPtvm/070.jpg",
      "https://i.postimg.cc/7Zg0mbfH/071.jpg",
      "https://i.postimg.cc/JhxJCg3V/077.jpg",
      "https://i.postimg.cc/Y9SFr388/078.jpg",
      "https://i.postimg.cc/LXsP9Tvb/079.jpg",
      "https://i.postimg.cc/3xVJ6Qbt/080.jpg",
      "https://i.postimg.cc/C16qzq64/081.jpg",
      "https://i.postimg.cc/htftptMw/083.jpg",
      "https://i.postimg.cc/c4JxLJqN/102.jpg",
      "https://i.postimg.cc/Y0rpgrhG/103.jpg",
      "https://i.postimg.cc/T3LTnHYN/104.jpg",
      "https://i.postimg.cc/SRBYGp49/105.jpg",
      "https://i.postimg.cc/PrFtpkh2/106.jpg"
    ]
  },
  {
    id: 19,
    title: '무진로 진아리채',
    year: '2022',
    py: '42PY',
    image: 'https://i.postimg.cc/mD6wBdv6/mua.png',
    category: '40PY',
    description: "무진로 진아리채 프로젝트는 공간의 여백을 살린 미니멀리즘과 실용적인 동선 설계가 돋보이는 현장입니다. 42평형의 넓은 공간감을 극대화하기 위해 화이트 베이스에 절제된 조명 계획을 적용하였으며, 고객의 라이프스타일을 반영한 맞춤 가구 제작으로 수납 효율과 심미성을 동시에 높였습니다. 군더더기 없는 마감과 차분한 톤앤매너가 어우러져 편안하고 고급스러운 주거 분위기를 선사합니다.",
    meta: [
      { label: "LOCATION", value: "Gwangsan-gu, Gwangju" },
      { label: "TYPE", value: "Residential" },
      { label: "AREA", value: "141m² / 42py" },
      { label: "YEAR", value: "2022" },
      { label: "DESIGN", value: "THE H BRAND co.,Ltd." },
    ],
    images: [
      "https://i.postimg.cc/Hk2vFtkF/059.jpg",
      "https://i.postimg.cc/1z37SN8B/060.jpg",
      "https://i.postimg.cc/9fQg2qDp/061.jpg",
      "https://i.postimg.cc/SKx14znV/062.jpg",
      "https://i.postimg.cc/XvY1Wyr1/063.jpg",
      "https://i.postimg.cc/g02tp6xN/064.jpg",
      "https://i.postimg.cc/VkYD9bW9/065.jpg",
      "https://i.postimg.cc/8CzXGr7Z/066.jpg",
      "https://i.postimg.cc/YSCD7mvy/067.jpg",
      "https://i.postimg.cc/Zq5smyWg/069.jpg",
      "https://i.postimg.cc/fbRqs0Vp/070.jpg",
      "https://i.postimg.cc/K8ZJ7gD5/075.jpg",
      "https://i.postimg.cc/3wxfhDkz/077.jpg",
      "https://i.postimg.cc/25S9YB1s/080.jpg",
      "https://i.postimg.cc/1z37SNgh/085.jpg",
      "https://i.postimg.cc/yN8pKSJC/086.jpg",
      "https://i.postimg.cc/vZQ376tL/087.jpg",
      "https://i.postimg.cc/6p9YVGff/088.jpg",
      "https://i.postimg.cc/zfG2NRL1/089.jpg",
      "https://i.postimg.cc/5t2KJFHV/090.jpg",
      "https://i.postimg.cc/TP3NxWyG/092.jpg",
      "https://i.postimg.cc/nLhSxQsx/093.jpg",
      "https://i.postimg.cc/5t2KJFHb/108.jpg",
      "https://i.postimg.cc/T3CQtYtb/109.jpg",
      "https://i.postimg.cc/yN8pKSJ6/113.jpg",
      "https://i.postimg.cc/Z5VjwKwy/157.jpg"
    ]
  }
];

const categories = ['ALL', '20PY', '30PY', '40PY', '50PY', 'ETC'];

const Portfolio: React.FC = () => {
  const [filter, setFilter] = useState('ALL');

  const filteredProjects = filter === 'ALL' 
    ? mockProjects 
    : mockProjects.filter(p => p.category === filter);

  return (
    <div className="pt-32 pb-20 px-4 md:px-10 min-h-screen bg-white">
      <div className="max-w-[1800px] mx-auto">
        
        {/* Header & Filter */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 px-2">
          <div>
            <h1 className="text-4xl md:text-6xl font-bold mb-4 text-brand-dark">PORTFOLIO</h1>
            <p className="text-gray-500">Premium spaces crafted by THE H BRAND.</p>
          </div>
          
          <div className="flex space-x-6 mt-8 md:mt-0 overflow-x-auto pb-2">
            {categories.map(cat => (
              <button
                key={cat}
                onClick={() => setFilter(cat)}
                className={`text-sm uppercase tracking-widest transition-colors whitespace-nowrap ${filter === cat ? 'text-brand-brown font-bold border-b border-brand-brown' : 'text-gray-400 hover:text-brand-dark'}`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* 4-Column Grid Layout */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-x-6 gap-y-12">
          {filteredProjects.map((project) => (
            <Link 
              key={project.id}
              to={`/portfolio/${project.id}`} 
              className="group block cursor-pointer"
            >
              {/* Image Container - Vertical Aspect Ratio 3:4 */}
              <div className="aspect-[3/4] relative mb-5">
                <LazyImage 
                  src={project.image} 
                  alt={project.title} 
                  className="w-full h-full object-cover transition-transform duration-700 ease-out group-hover:scale-105"
                  containerClassName="w-full h-full bg-gray-100"
                />
              </div>

              {/* Info Bar */}
              <div className="flex justify-between items-start border-t border-transparent pt-1">
                <div className="flex flex-col pr-4">
                  <span className="text-brand-dark font-bold text-sm md:text-base mb-1 leading-tight group-hover:text-brand-brown transition-colors">
                    {project.title}
                  </span>
                  <span className="text-gray-400 text-xs font-light tracking-wide">
                    {project.year}
                  </span>
                </div>
                <span className="text-brand-dark text-sm font-medium tracking-wide whitespace-nowrap">
                  {project.py}
                </span>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Portfolio;